{
 "title": "Url Shortener Auth Service",
 "description": "UrlShortener Auth Service Dashboard",
 "tags": [
  "go",
  "auth-service",
  "microservice"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job_name", "label": "Job Name", "query": "${VAR_JOB_NAME}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{instance=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{instance=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{instance=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{instance=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total HTTP Requests (Grouped by Path)",
   "type": "timeseries",
   "description": "Shows the total count of HTTP requests grouped by method, path, and status. Useful for understanding traffic patterns and error rates.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (\n  increase(urlshortener_api_gateway_requests_total{instance=~\"$instance\"}[$__range])\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Over Time Range",
   "type": "gauge",
   "description": "Displays the total number of requests counted during the selected time range.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(authservice_http_requests_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 4xx or 5xx Responses",
   "type": "gauge",
   "description": "Shows total 4xx/5xx errors within the Grafana-selected time range",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(authservice_http_requests_total{status=~\"4..|5..\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Displays the average response time (in seconds) grouped by endpoint, method, and status code.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(authservice_http_request_duration_seconds_sum{instance=~\"$instance\"}[$__range])) by (path) \n/\nsum(rate(authservice_http_request_duration_seconds_count{instance=~\"$instance\"}[$__range])) by (path)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx & 5xx Errors",
   "type": "timeseries",
   "description": "Displays the number of client (4xx) and server (5xx) errors together over time, grouped by path, method, and status code.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path, method, status) (\n  increase(authservice_http_requests_total{status=~\"4..|5..\", instance=~\"$instance\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Average Response Time",
   "type": "timeseries",
   "description": "Displays the average response time across all endpoints.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(authservice_http_request_duration_seconds_sum{instance=~\"$instance\"}[$__range])) \n/\nsum(rate(authservice_http_request_duration_seconds_count{instance=~\"$instance\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 & p99 Response Times (All Requests)",
   "type": "timeseries",
   "description": "Displays the 95th percentile (p95) and 99th percentile (p99) response times for all HTTP requests, regardless of method, path, or status code. The graph helps identify high-latency requests and track performance trends over time.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(authservice_http_request_duration_seconds_bucket{instance=~\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(authservice_http_request_duration_seconds_bucket{instance=~\"$instance\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}