{
 "title": "Url Shortener Statistics Service",
 "description": "A quickstart to setup the Prometheus Node.js Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "microservice",
  "node.js",
  "statistics-service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "This panel displays the exact timestamp of when the Node.js application started, based on the process_start_time_seconds metric. The timestamp is shown in a human-readable format and is adjusted to the local timezone of the user's browser for better clarity.",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "stat",
   "description": "Displays the uptime of the Node.js application, calculated from the process start time.",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU usage.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[$__range]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
       "legendFormat": "System CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
       "legendFormat": "Total CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Time Spent",
     "type": "timeseries",
     "description": "CPU time spent.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Process Memory - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers and Requests",
     "type": "timeseries",
     "description": "Number of active handle and active requests.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
       "legendFormat": "Active Handler - {{instance}}"
      },
      {
       "expr": "nodejs_active_requests_total{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Active Request - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Latency",
     "type": "timeseries",
     "description": "Latency of the event loop.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
       "legendFormat": "Last - {{instance}}"
      },
      {
       "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "P99 - {{instance}}"
      },
      {
       "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "P50 - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Duration Rate",
     "type": "timeseries",
     "description": "Rate of garbage collection duration.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum{instance=\"$instance\"}[$__range])",
       "legendFormat": "{{kind}} - {{instance}}"
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "timeseries",
     "description": "Duration of garbage collection.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_sum{instance=\"$instance\"}",
       "legendFormat": "{{kind}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "timeseries",
     "description": "Usage of heap memory.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Total - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Used - {{instance}}"
      },
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Resident - {{instance}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "External - {{instance}}"
      }
     ]
    },
    {
     "title": "GC Rate",
     "type": "timeseries",
     "description": "Rate of garbage collection.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_count{instance=\"$instance\"}[$__range])",
       "legendFormat": "{{instance}} - {{kind}}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "timeseries",
     "description": "Count of garbage collection.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{kind}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Space Used",
     "type": "timeseries",
     "description": "Usage of heap space.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{space}} - {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total HTTP Requests",
   "type": "gauge",
   "description": "Displays the overall count of incoming HTTP requests for the selected service.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\"})",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Total HTTP Error Requests (4xx/5xx)",
   "type": "gauge",
   "description": "This panel displays the total count of HTTP requests that resulted in client or server errors (status codes in the 4xx and 5xx range) for the selected job and instance. Requests related to Prometheus endpoints are excluded, allowing you to focus on user-facing error responses.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\", status_code=~\"4..|5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Count (Selected Time Range)",
   "type": "gauge",
   "description": "This gauge panel displays the total increase in HTTP requests over the currently selected time range. It dynamically calculates the increase for the chosen job and instance while excluding any endpoints containing \"prometheus,\" providing a clear view of request activity within the specified period.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Request Increase (4xx/5xx)",
   "type": "gauge",
   "description": "This gauge panel displays the increase in HTTP error requests—those with client or server error status codes (4xx and 5xx)—over the currently selected time range. It dynamically calculates the error count for the specified job and instance while excluding any endpoints related to Prometheus, providing clear insight into error trends during the chosen period.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\", status_code=~\"4..|5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Path",
   "type": "timeseries",
   "description": "Presents a breakdown of requests based on URL paths for the selected service, excluding those containing \"prometheus\" to focus on user-relevant endpoints.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(path) (http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status Code",
   "type": "timeseries",
   "description": " Illustrates the distribution of responses by status code, giving insight into success and error rates while filtering out URLs that include \"prometheus\".",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status_code) (http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "description": "Shows the distribution of incoming requests by HTTP method (such as GET or POST) for the selected service, while filtering out requests with \"prometheus\" in the URL.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method) (http_requests_total{instance=~\"$instance\", path!~\".*prometheus.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}