{
 "title": "Url Shortener Service",
 "description": "Spring Boot Dashboard adapted from https://grafana.com/grafana/dashboards/10280-microservices-spring-boot-2-1/",
 "tags": [
  "microservice",
  "spring-boot",
  "urlshortener-service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_name", "label": "Job Name", "query": "${VAR_JOB_NAME}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{job=\"$job_name\"},instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{job=\"$job_name\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job_name\",instance=\"$instance\", area=\"heap\"}) \n  * 100 \n/ sum(jvm_memory_max_bytes{job=\"$job_name\",instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job_name\", instance=\"$instance\", area=\"nonheap\"}) \n  * 100 \n/ sum(jvm_memory_max_bytes{job=\"$job_name\", instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "process_files_open_files{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "Open Files"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"$job_name\", instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 277 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$job_name\", instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{job=\"$job_name\", instance=\"$instance\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 298 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{job=\"$job_name\", instance=\"$instance\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{job=\"$job_name\", instance=\"$instance\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{job=\"$job_name\", instance=\"$instance\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$job_name\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$job_name\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{job=\"$job_name\", instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{job=\"$job_name\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{job=\"$job_name\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$job_name\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$job_name\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{job=\"$job_name\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{job=\"$job_name\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total HTTP Requests",
   "type": "gauge",
   "description": "Displays the cumulative total number of HTTP requests handled by the application since startup. The value increases continuously and resets only when the application restarts.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"$job_name\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests (Excluding Prometheus Paths)",
   "type": "gauge",
   "description": "Shows the total number of HTTP requests received within the selected time range, excluding requests to paths containing \"prometheus\". Provides insight into application traffic while filtering out monitoring endpoints.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job_name\", instance=\"$instance\", uri!~\".*prometheus.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 4xx and 5xx HTTP Requests",
   "type": "gauge",
   "description": "Displays the total number of client (4xx) and server (5xx) error responses received within the selected time range. Helps monitor application issues and identify potential failures impacting users.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job_name\", instance=\"$instance\", status=~\"4..|5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{job=\"$job_name\", instance=\"$instance\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]) \n/ \nirate(http_server_requests_seconds_count{job=\"$job_name\", instance=\"$instance\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{job=\"$job_name\", instance=\"$instance\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}